### PR TITLE
fix for workflow builds

### PR DESCRIPTION
**Pull request by deepak7093**
- Fix github workflow fails if any docker build has error

### CODE REVIEW

**Review by kili-ilo — COMMENTED** [review]
Great idea, @deepak7093 ! Will this still show as a red failure in GH to alert us?

**Comment by deepak7093** [comment]
@JanCVanB Added red color for fail builds

**Comment by kili-ilo** [comment]
Sorry, what I meant to ask is will this prevent the PR page on GH from showing a failing build status? We want any failed `docker build` to make its GH action/job/workflow fail (and mark the PR as potentially broken). I'm concerned that this change will silence real bugs, since we won't inspect workflow logs if GH tags the workflow as green.

**Comment by deepak7093** [comment]
> Sorry, what I meant to ask is will this prevent the PR page on GH from showing a failing build status? We want any failed `docker build` to make its GH action/job/workflow fail (and mark the PR as potentially broken). I'm concerned that this change will silence real bugs, since we won't inspect workflow logs if GH tags the workflow as green.

@JanCVanB Got it, added exit 1 in case of `docker build` fails. Added `if: always()` condition to continue workflow execution even if step/job fails.

**Comment by kili-ilo** [comment]
@deepak7093 Sorry for my absence here - can you remind me of the motivation for this PR? What problem is it solving? Can you link me an example of a "bad" run from before this PR?

**Comment by deepak7093** [comment]
> @deepak7093 Sorry for my absence here - can you remind me of the motivation for this PR? What problem is it solving? Can you link me an example of a "bad" run from before this PR?

@JanCVanB Problem Statement is: During docker build for all apps, if any build fails it stop execution for rest as well. So it's all or nothing scenario. We are trying to bypass failed builds and publish other succeed image builds.

**Comment by kili-ilo** [comment]
@deepak7093 Thanks for that explanation, but I believe that it currently builds all images in parallel, without any "fail-fast" or "early cancellation" behavior that I think you're describing. Do you agree?

See [this run](https://github.com/itopia-inc/spaces-images/actions/runs/1749809685)

The only dependency that I see is that the externally-triggered workflow [doesn't build any prod images](https://github.com/itopia-inc/spaces-images/actions/runs/1712654519) unless all dev image builds succeed, and I'm open to changing that rule.

**Comment by deepak7093** [comment]
> @deepak7093 Thanks for that explanation, but I believe that it currently builds all images in parallel, without any "fail-fast" or "early cancellation" behavior that I think you're describing. Do you agree?
> 
> See [this run](https://github.com/itopia-inc/spaces-images/actions/runs/1749809685)
> 
> The only dependency that I see is that the externally-triggered workflow [doesn't build any prod images](https://github.com/itopia-inc/spaces-images/actions/runs/1712654519) unless all dev image builds succeed, and I'm open to changing that rule.

Sound good @JanCVanB Go ahead and change the rule

**Pull request closed without merging**
